### ISSUE TITLE
When mouse hovers over file, the shapefile highlights itself

### ISSUE THREAD

**Issue by claraarnold** [cs481-ekh/s24-healthy-idaho#121]
References User Story #24

**Comment by BraedenL** [comment]
The shapefile updates, however needs fix to make it so that color is retained while highlight is in effect. Personally updating myself and checking in on the frontside.

[t:180]

**Comment by BraedenL** [comment]
Finished and adjusted the program to highlight the census district a yellow color when hovered over. Fix the error where the map would revert to plain color.

[t:120]
